### ISSUE TITLE
dotenv works differently in 'build' vs 'run' if the project is in a workspace

### ISSUE THREAD

**Issue by limira** [purpliminal/rust-dotenv#101]
I am actually using [`diesel`](https://github.com/diesel-rs/diesel) which is in turn relied on `dotenv`. In an app that use `diesel` and its `infer_schema!` macro, a database url is required for `diesel` to inspect the database schema. It is used like this:

    infer_schema!("dotenv:DATABASE_URL");

In this case, the `infer_schema!` try to load the `.env` file before getting value of `DATABASE_URL`. This works correctly in standalone projects. But with projects inside a **workspace** it does not work if the `.env` file is in the project root.
```
workspace\
    |--- Cargo.toml
    |--- .env // DATABASE_URL in here, it works for infer_schema!
    |--- projects\
         |--- libs\....
         |--- apps\
              |--- project1\
                   |--- Cargo.toml
                   |--- .env // DATABASE_URL in here, it DOES NOT work for infer_schema!
                             // But work correctly in main(), see more bellow
                   |--- src\...
```
But if I only use it inside main(),
```
fn main() {
    dotenv::dotenv().ok();
    let url = std::env::var("DATABASE_URL").expect("DATABASE_URL not found");
    // No panic from the line above and `url` have correct value of DATABASE_URL
}
```
The `infer_schema` execute at `build` time, `main` execute at `run` time. So I think there are some inconsistency in the way `dotenv` works in `cargo build` vs `cargo run`. (Both `cargo build` and `cargo run` run inside the `project1` folder.)

**Comment by daboross** [comment]
I don't think this is something we can fix in dotenv - this will need to be fixed within diesel's infer_schema, or cargo?

In dotenv, we always search from the current working directory up. This works well at runtime, because you're running your crate in the directory you want to. But at compile time, cargo runs all procedural macros with the current working directory equal to the workspace crate.

To fix this, you either need to put all you `.env` files in the workspace root, or diesel needs to change how it is using `dotenv` (see https://github.com/diesel-rs/diesel/issues/1696#issuecomment-390354612).

**Comment by purpliminal** [comment]
This issue seems like a repeat of #71, and I feel like the arguments for and against this issue that were raised then still stand. I'm closing this, but feel free to reopen it if you wish to discuss it further.
