### ISSUE TITLE
Does not work if variable depends on another env var.

### ISSUE THREAD

**Issue by asdetrefle** [purpliminal/rust-dotenv#94]
When i tried to define a log path in `.env` file with `$HOME` variable

`RUST_LOG_PATH=$HOME/logs/rust.log`

it fails to parse. Is there any special reason why this is not supported? 

Also I feels like it stops parsing all the variables defined after this one unless i missed some point. In other word, if i put this line on top of my `.env` file, no variable from the file will be parsed. Maybe this is a separate issue.

**Comment by purpliminal** [comment]
Hi, thanks for reporting!

When char-by-char parsing was introduced (#32), [unescaped dollar signs on unquoted or doubly quoted values became parsing errors](https://github.com/purpliminal/rust-dotenv/pull/32#issuecomment-183662984). Try using single quotes, as in `RUST_LOG_PATH='$HOME/logs/rust.log'`

The idea behind disallowing dollar signs was to be able to implement environment variable interpolation later on: that is, so that instead of failing, `$HOME/logs/rust.log` becomes `/home/asdetrefle/logs/rust.log`. This has not been implemented yet: I have just created issue #95 for it. PRs are always welcome!
